In [9]:
import warnings
warnings.filterwarnings('ignore')

# Evaluation Framework

In [10]:
from sdv.demo import load_tabular_demo
from sdv.tabular import GaussianCopula

In [11]:
real_data = load_tabular_demo('student_placements')
real_data

,student_id,gender,second_perc,high_perc,high_spec,degree_perc,degree_type,work_experience,experience_years,employability_perc,mba_spec,mba_perc,salary,placed,start_date,end_date,duration
0,17264,M,67.00,91.00,Commerce,58.00,Sci&Tech,False,0,55.0,Mkt&HR,58.80,27000.0,True,2020-07-23,2020-10-12,3.0
1,17265,M,79.33,78.33,Science,77.48,Sci&Tech,True,1,86.5,Mkt&Fin,66.28,20000.0,True,2020-01-11,2020-04-09,3.0
2,17266,M,65.00,68.00,Arts,64.00,Comm&Mgmt,False,0,75.0,Mkt&Fin,57.80,25000.0,True,2020-01-26,2020-07-13,6.0
3,17267,M,56.00,52.00,Science,52.00,Sci&Tech,False,0,66.0,Mkt&HR,59.43,NaN,False,NaT,NaT,NaN
4,17268,M,85.80,73.60,Commerce,73.30,Comm&Mgmt,False,0,96.8,Mkt&Fin,55.50,42500.0,True,2020-07-04,2020-09-27,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,17474,M,80.60,82.00,Commerce,77.60,Comm&Mgmt,False,0,91.0,Mkt&Fin,74.49,40000.0,True,2020-07-27,2020-10-20,3.0
211,17475,M,58.00,60.00,Science,72.00,Sci&Tech,False,0,74.0,Mkt&Fin,53.62,27500.0,True,2020-01-23,2020-08-04,6.0
212,17476,M,67.00,67.00,Commerce,73.00,Comm&Mgmt,True,1,59.0,Mkt&Fin,69.72,29500.0,True,2020-01-25,2020-08-05,6.0
213,17477,F,74.00,66.00,Commerce,58.00,Comm&Mgmt,False,0,70.0,Mkt&HR,60.23,20400.0,True,2020-01-19,2020-04-20,3.0
214,17478,M,62.00,58.00,Science,53.00,Comm&Mgmt,False,0,89.0,Mkt&HR,60.22,NaN,False,NaT,NaT,NaN

In [12]:
model = GaussianCopula()
model.fit(real_data)
synthetic_data = model.sample()

In [13]:
synthetic_data

,student_id,gender,second_perc,high_perc,high_spec,degree_perc,degree_type,work_experience,experience_years,employability_perc,mba_spec,mba_perc,salary,placed,start_date,end_date,duration
0,17275,F,76.18,61.64,Science,66.33,Sci&Tech,False,0,77.41,Mkt&Fin,62.18,NaN,False,NaT,NaT,NaN
1,17345,F,77.03,81.39,Commerce,64.69,Others,False,0,54.43,Mkt&Fin,63.10,NaN,False,NaT,NaT,NaN
2,17343,M,70.79,69.19,Commerce,73.36,Comm&Mgmt,False,0,66.01,Mkt&Fin,67.06,23600.0,True,2020-01-02,2020-02-13,4.0
3,17383,M,71.62,97.70,Commerce,72.39,Comm&Mgmt,False,1,58.95,Mkt&Fin,60.12,32500.0,True,2020-03-13,2020-09-17,6.0
4,17432,M,53.00,38.87,Commerce,52.48,Comm&Mgmt,False,0,69.85,Mkt&HR,54.97,NaN,False,NaT,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,17410,M,68.39,62.88,Science,64.65,Comm&Mgmt,False,0,73.07,Mkt&HR,57.13,24200.0,True,2020-02-17,2020-08-22,5.0
211,17392,F,69.77,79.70,Commerce,63.46,Comm&Mgmt,False,0,74.75,Mkt&Fin,65.69,26300.0,True,2020-04-17,2020-07-09,3.0
212,17458,F,46.35,64.36,Commerce,60.90,Comm&Mgmt,False,0,85.49,Mkt&HR,69.49,NaN,False,NaT,NaT,NaN
213,17412,M,68.57,71.70,Science,59.84,Others,False,1,56.15,Mkt&HR,69.71,23700.0,True,2020-01-15,2020-09-13,8.0
214,17309,M,83.49,74.97,Science,73.95,Sci&Tech,False,0,71.09,Mkt&Fin,70.18,29700.0,True,2020-04-03,2020-07-18,3.0

## Evaluate Framework

In [14]:
from sdv.evaluation import evaluate

In [15]:
evaluate(synthetic_data, real_data, 
         aggregate=False, 
#          metrics=['CSTest', 'KSTest'],
        )

,metric,name,raw_score,normalized_score,min_value,max_value,goal
0,BNLogLikelihood,BayesianNetwork Log Likelihood,-4.052218,1.738378e-02,-inf,0.0,MAXIMIZE
1,LogisticDetection,LogisticRegression Detection,0.477096,4.770964e-01,0.0,1.0,MAXIMIZE
2,SVCDetection,SVC Detection,0.439675,4.396753e-01,0.0,1.0,MAXIMIZE
11,GMLogLikelihood,GaussianMixture Log Likelihood,-37.538229,4.981434e-17,-inf,inf,MAXIMIZE
12,CSTest,Chi-Squared,0.891862,8.918625e-01,0.0,1.0,MAXIMIZE
13,KSTest,Inverted Kolmogorov-Smirnov D statistic,0.915245,9.152455e-01,0.0,1.0,MAXIMIZE
14,KSTestExtended,Inverted Kolmogorov-Smirnov D statistic,0.917386,9.173865e-01,0.0,1.0,MAXIMIZE
27,ContinuousKLDivergence,Continuous Kullback–Leibler Divergence,0.492551,4.925508e-01,0.0,1.0,MAXIMIZE
28,DiscreteKLDivergence,Discrete Kullback–Leibler Divergence,0.884175,8.841753e-01,0.0,1.0,MAXIMIZE

## Single Table Metric Families
The `Single Table Metrics` are grouped in multiple families:

### Statistical Metrics
**Statistical Metrics**: The metrics of this family compare the tables by running different types of statistical tests on them.In the most simple scenario, these metrics compare individual columns from the real table with the corresponding column from the synthetic table, and at the end report the average outcome from the test.
- `sdv.metrics.tabular.KSTest`: This metric uses the two-sample Kolmogorov–Smirnov test to compare the distributions of continuous columns using the empirical CDF. The output for each column is 1 minus the KS Test D statistic, which indicates the maximum distance between the expected CDF and the observed CDF values.
- `sdv.metrics.tabular.CSTest`: This metric uses the Chi-Squared test to compare the distributions of two discrete columns. The output for each column is the CSTest p-value, which indicates the probability of the two columns having been sampled from the same distribution.

In [16]:
 from sdv.metrics.tabular import CSTest, KSTest

In [17]:
CSTest.compute(real_data, synthetic_data)

0.8918624825411982

In [18]:
KSTest.compute(real_data, synthetic_data)

0.9152454780361757

### Likelihood Metrics
**Likelihood Metrics**: The metrics of this family compare the tables by fitting the real data to a probabilistic model and afterwards compute the likelihood of the synthetic data belonging to the learned distribution.
- `sdv.metrics.tabular.BNLikelihood`: This metric fits a BayesianNetwork to the real data and then evaluates the average likelihood of the rows from the synthetic data on it.
- `sdv.metrics.tabular.BNLogLikelihood`: This metric fits a BayesianNetwork to the real data and then evaluates the average log likelihood of the rows from the synthetic data on it.
- `sdv.metrics.tabular.GMLogLikelihood`: This metric fits multiple GaussianMixture models to the real data and then evaluates the average log likelihood of the synthetic data on them.

In [19]:
from sdv.metrics.tabular import BNLikelihood, BNLogLikelihood, GMLogLikelihood

In [20]:
BNLikelihood.compute(real_data.fillna(0), synthetic_data.fillna(0))

0.005415897509014583

In [21]:
BNLogLikelihood.compute(real_data.fillna(0), synthetic_data.fillna(0))

-13.468003674979125

In [22]:
GMLogLikelihood.compute(real_data.fillna(0), synthetic_data.fillna(0))

-27.23624319750103

### Detection Metrics
**Detection Metrics**: The metrics of this family evaluate how hard it is to distinguish the synthetic data from the real data by using a Machine Learning model. To do this, the metrics will shuffle the real data and synthetic data together with flags indicating whether the data is real or synthetic, and then cross validate a Machine Learning model that tries to predict this flag. The output of the metrics will be the 1 minus the average ROC AUC score across all the cross validation splits.
- `sdv.metrics.tabular.LogisticDetection`: Detection metric based on a LogisticRegression classifier from scikit-learn.
- `sdv.metrics.tabular.SVCDetection`: Detection metric based on a SVC classifier from scikit-learn.

In [23]:
from sdv.metrics.tabular import LogisticDetection, SVCDetection

In [24]:
LogisticDetection.compute(real_data, synthetic_data)

0.4674313887439866

In [25]:
SVCDetection.compute(real_data, synthetic_data)

0.4378984814235206

### Machine Learning Efficacy Metrics
**Machine Learning Efficacy Metrics**: This family of metrics will evaluate whether it is possible to replace the real data with synthetic data in order to solve a Machine Learning Problem by learning a Machine Learning model on the synthetic data and then evaluating the score which it obtains when evaluated on the real data. The metrics on this family are organized by Machine Learning problem type and model.
- Binary Classification Metrics:
    - BinaryDecisionTreeClassifier
    - BinaryAdaBoostClassifier
    - BinaryLogisticRegression
    - BinaryMLPClassifier
- Multiclass Classification Metrics:
    - MulticlassDecisionTreeClassifier
    - MulticlassMLPClassifier
- Regression Metrics:
    - LinearRegression
    - MLPRegressor

In [26]:
from sdv.metrics.tabular import MulticlassDecisionTreeClassifier

In [27]:
MulticlassDecisionTreeClassifier.compute(real_data, synthetic_data, target='mba_spec')

0.5375741380434074

### Privacy Metrics
**Privacy Metrics**: This family of metrics measures the privacy of a synthetic dataset by positing the question: given the synthetic data, can an attacker predict sensitive attributes in the real dataset? These models accomplish this by fitting an adversarial attacker model on the synthetic data to predict sensitive attributes from “key” attributes and then evaluating its accuracy on the real data.
- Categorical metrics:
    - `sdv.metrics.tabular.CategoricalCAP`
    - `sdv.metrics.tabular.CategoricalZeroCAP`
    - `sdv.metrics.tabular.CategoricalGeneralizedCAP`
    - `sdv.metrics.tabular.CategoricalKNN`
    - `sdv.metrics.tabular.CategoricalNB`
    - `sdv.metrics.tabular.CategoricalRF`
    - `sdv.metrics.tabular.CategoricalEnsemble`
- Numerical metrics:
    - `sdv.metrics.tabular.NumericalMLP`
    - `sdv.metrics.tabular.NumericalLR`
    - `sdv.metrics.tabular.NumericalSVR`
    - `sdv.metrics.tabular.NumericalRadiusNearestNeighbor`

In [28]:
from sdv.metrics.tabular import NumericalMLP

NumericalMLP.compute(real_data.fillna(0),
                    synthetic_data.fillna(0),
                    key_fields=['second_perc', 'mba_perc', 'degree_perc'],
                    sensitive_fields=['salary']
                   )

0.147239865808757